name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build realify
      run: |
        export HASH=$(git rev-parse HEAD)
        export REV=latest
        make
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "${{ env.GITHUB_SHA }}"
        files: |
          *.zip
          *.sha
